EE:
  name: 双床标间（1.2 米床）
  bookable: true
  prices:
    user:
      weekly:
        currency: CNY ￥
        amount: 800
      monthly:
        currency: CNY ￥
        amount: 2160
        discount: 0.32
    starStruck1:
      monthly:
        currency: CNY ￥
        amount: 1920
    starStruck2:
      monthly:
        currency: CNY ￥
        amount: 1800
    starStruck3:
      monthly:
        currency: CNY ￥
        amount: 1600
      daily:
        currency: CNY ￥
        amount: 54
Max:
  name: 大床房（无暖气）
  bookable: false
  prices:
    user:
      weekly:
        currency: CNY ￥
        amount: 1024
      monthly:
        currency: CNY ￥
        amount: 2560
        discount: 0.37
    starStruck1:
      monthly:
        currency: CNY ￥
        amount: 2160
    starStruck2:
      monthly:
        currency: CNY ￥
        amount: 1920
    starStruck3:
      monthly:
        currency: CNY ￥
        amount: 1800
      daily:
        currency: CNY ￥
        amount: 60
